--- # change port
server:
  port: 8088

--- # thymeleaf
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hanwoori
    username: root
    password: 1234
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: knou.seoul